const strings = {
	en: {
		title: 'Orders',
		tableOrderNumber: 'Order #',
		tableEmail: 'email',
		tableTotal: 'Total',
		tableDate: 'Date',
		tableStatus: 'Status',
		tablePayment: 'Payment Method',
		searchBy: 'Search by',
		searchNone: '--- No Filter ---',
		searchState: 'status',
		searchMin: 'min amount',
		searchMax: 'max amount',
		searchPayment: 'payment method',
		searchUserId: 'user id',
		searchCreatedAt: 'date',
		completed: 'completed',
		created: 'created',
		processing: 'processing',
		canceled: 'canceled',
		button: 'Search',
		noMatch: 'No Matches',
	},

	es: {
		title: 'Órdenes',
		tableOrderNumber: 'N° Orden',
		tableEmail: 'email',
		tableTotal: 'Total',
		tableDate: 'Fecha',
		tableStatus: 'Estado',
		tablePayment: 'Método de pago',
		searchBy: 'Buscar por',
		searchNone: '--- Sin filtro ---',
		searchState: 'estado',
		searchMin: 'menor que',
		searchMax: 'mayor que',
		searchPayment: 'metodo de pago',
		searchUserId: 'id de usuario',
		searchCreatedAt: 'fecha',
		completed: 'completada',
		created: 'creada',
		processing: 'en proceso',
		canceled: 'cancelada',
		button: 'Buscar',
		noMatch: 'Sin coincidencias',
	}
};

export default strings;