export default {
	en: {
		email: 'Email',
		login: 'Login',
		signUp: 'Sign up',
		details: 'Customer details',
		cardNumber: 'Card number',
		name: 'Full name',
		expiry: 'Expiry date',
		next: 'Next',
		emailParagraph: 'You are logged in. The purchase will be made with the following email:',
		warning: 'You will continue the payment process on the Mercadopago platform. Once completed you will be redirected to Gaming Hub',
		info: 'Enter your email to continue or you can log in.',
		paymentTitle: 'Select the payment method',
	},
	es: {
		email: 'Correo',
		login: 'Iniciar sesión',
		signUp: 'Registrarse',
		details: 'Datos de cliente',
		cardNumber: 'Número de tarjeta',
		name: 'Nombre completo',
		expiry: 'Fecha de vencimiento',
		next: 'Siguiente',
		emailParagraph: 'Ya iniciaste sesión. Usaremos el siguiente mail para realizar la compra:',
		warning: 'Continuaras el proceso de pago en la plataforma de mercadopago. Una vez completado volveras a Gaming Hub',
		info: 'Ingresa tu correo para continuar o puedes iniciar sesión.',
		paymentTitle: 'Selecciona el metodo de pago',
	}
}