const strings = {
	en: {
		language: 'Language',
		user: 'User',
		cart: 'Cart',
		categories: 'Categories',
		offer: 'Offers',
		about: 'About us',
		theme: 'Theme',
		logout_confirm: 'You are about to log out',
		logout_confirm_text: 'Are you sure?',
		logout_button: 'Yes',
		logout_confirm_2: '',
		logout_confirm_text2: 'You have successfully logged out.',
		login: 'Log In',
		signup: 'Sign Up',
		logout: 'Log Out',
		admin: 'Administration Panel',
		profile: 'Profile',
	},
	es: {
		language: 'Idioma',
		user: 'Usuario',
		cart: 'Carrito',
		categories: 'Categorías',
		offer: 'Ofertas',
		about: 'Conócenos',
		theme: 'Tema',
		logout_confirm: 'Estás por cerrar sesión',
		logout_confirm_text: '¿Seguro de que quieres hacerlo?',
		logout_button: 'Sí',
		logout_confirm_2: '',
		logout_confirm_text_2: 'Has cerrado sesión correctamente.',
		login: 'Iniciar sesión',
		signup: 'Registrarse',
		logout: 'Cerrar sesión',
		admin: 'Panel de administración',
		profile: 'Perfil',
	}
};

export default strings;