const strings = {
	en: {
		language: 'Language',
		language_en: "English",
		language_es: "Spanish",
		user: 'User',
		cart: 'Cart',
		categories: 'Categories',
		offer: 'Offer',
		about: 'About',
		theme: 'Theme',
		logout_confirm: 'Close Session!',
		logout_confirm_text: 'Are you sure?',
		logout_button: 'Yes!',
		logout_confirm_text2: 'You have successfully logged out',
		login: 'Log In',
		signup: 'Sign Up',
		logout: 'Log Out',
		admin: 'Administration Panel',
		profile: 'Profile',
	},
	es: {
		language: 'Idioma',
		language_en: "Inglés",
		language_es: "Español",
		user: 'Usuario',
		cart: 'Carrito',
		categories: 'Categorias',
		offer: 'Ofertas',
		about: 'Conocenos',
		theme: 'Tema',
		logout_confirm: 'Cerrar Sesión!',
		logout_confirm_text: '¿Estás Seguro?',
		logout_button: 'Si!',
		logout_confirm_text_2: 'Has cerrado sesión correctamente',
		login: 'Iniciar Sesión',
		signup: 'Regístrate',
		logout: 'Cerrar Sesión',
		admin: 'Panel de Administración',
		profile: 'Perfil',
	}
};

export default strings;